# Results of Computing F matrix

In [64]:
# Imports
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from importlib import reload
import EightPoint
reload(EightPoint)
from EightPoint import EightPoint
from processSequence import Sequence

## Get data

In [65]:
EPA = EightPoint()

# Load data
sequence = Sequence('./Reference_Render_cubes/Reference_Render_Translation')

['./Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0001.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0002.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0003.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0004.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0005.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0006.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0007.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0008.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0009.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0010.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0011.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation00

## Find keypoints

In [66]:
im1 = sequence.images[0]
im2 = sequence.images[1]
pts1, pts2 = EPA.getMatchingPointsOpenCV(im1, im2)

In [67]:
print(len(pts1))

255


## Compute F using our algorithm

In [68]:

F, consensus = EPA.getFundamentalRANSAC(pts1, pts2)

F_cv, mask = cv2.findFundamentalMat(pts1, pts2, cv2.RANSAC, 1)

NORM 1.0111465353090618
NORM 2.3623769434285125
Best number of inliers: 11, outliers: 244
NORM 1.0060916340667616
NORM 3.9733296137621363
Best number of inliers: 60, outliers: 195
NORM 1.0067777380891652
NORM 5.4081081410309135
NORM 1.0003283897817314
NORM 1.1541677769332055
Best number of inliers: 209, outliers: 46
NORM 1.0087088897828362
NORM 2.3138385479064865
NORM 1.0347304349999575
NORM 1.1689947854000293
NORM 98.59899190038406
NORM 1.1855842646274186
NORM 2.4408270129112504
NORM 2.8325325476367356
NORM 1.6141300722963576
NORM 1.0005521149953616
NORM 1.1541677769332055
NORM 2.530125157342132
NORM 2.3488482171367497
NORM 1.008700645195022
NORM 2.9353519005344983
NORM 2.3953994884960204
NORM 3.3976132639805905
NORM 1.0187337269247125
NORM 2.3623769434285125
NORM 1199899919318.465
NORM 2191001601494.423
NORM 19.06920999800612
NORM 327.0276669103072
NORM 1.0099836276157224
NORM 2.3623769434285125
NORM 1.0446161925759214
NORM 2.8230419218799416
NORM 1.0008219764510602
NORM 1.7362992762

c:\Users\Home\Documents\GitHub\Comp558Project\8PointAlgorithm\EightPoint.py:99: RuntimeWarning: divide by zero encountered in divide
  Fnormalized = U @ np.diag(S) @ Vt
c:\Users\Home\Documents\GitHub\Comp558Project\8PointAlgorithm\EightPoint.py:99: RuntimeWarning: invalid value encountered in divide
  Fnormalized = U @ np.diag(S) @ Vt
c:\Users\Home\Documents\GitHub\Comp558Project\8PointAlgorithm\EightPoint.py:132: RuntimeWarning: invalid value encountered in matmul
  


NORM 1.0229532453294707
NORM 1.2159511390775648
NORM 1.0622804789009685
NORM 1.0740654044794415
NORM 1.0176907534055482
NORM 1.0238292626274537
NORM 1.000064998118525
NORM 2.8230419218799416
NORM 1.0538101650059832
NORM 1.1689947854000293
NORM 2.097927201087128
NORM 9.087136891033726
NORM 1.256333824563278
NORM 1.2511330037448511
NORM 1.00047171466817
NORM 1.7362992762003229
NORM 1.000025778351774
NORM 1.0023362359190195
NORM 1.0093221348165315
NORM 5.616778469730147
NORM 1.703342461789272
NORM 1.9230172297755486
NORM 1.1001437415979531
NORM 1.6705876171834027
NORM 4464029865061.451
NORM 3942444161012.8813
NORM 1.1059256502635937
NORM 13.93558328821968
NORM 1.0630986656179717
NORM 7.833605813544367
NORM 1.0014156139499255
NORM 2.8230419218799416
NORM 29.225595777083456
NORM 136.74736220686916
NORM 1.0006844719442054
NORM 1.8327655316216263
NORM 1.3320730432562948
NORM 7.609980349099068
NORM 1.0097618683580363
NORM 1.2159511390775648
NORM 1.7073091562630964
NORM 1.8543840200026853
NORM 

In [69]:
number_of_pts = pts1.shape[0]
consensus_set = np.arange(0, number_of_pts)
consensus_set = np.isin(consensus_set, consensus)
print(sum(consensus_set))
consensus_set



223


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,

In [70]:
consensus_pts1 = pts1[consensus_set]
consensus_pts2 = pts2[consensus_set]



In [71]:
print(F)
print(F_cv)

[[-1.90761725e-07 -1.77833750e-05  9.37267206e-03]
 [ 1.88203814e-05  1.83704435e-06 -3.20876497e-03]
 [-9.68777047e-03  2.93918031e-04  1.00000000e+00]]
[[-1.83956216e-22  8.26674708e-18 -4.87231898e-15]
 [-8.18629689e-18  2.51406829e-21 -2.28942716e-02]
 [ 4.81591336e-15  2.28942716e-02  3.73034936e-14]]


## Compare the F we calculated with F calculated from our Ransac Consensus Points on opencv's cv2.findFundamentalMat(masked_pts1, masked_pts2, cv2.FM_8POINT)

In [72]:
def __getNormalizingMatrix(pts):
    # Normalize points
    ptsMean = np.mean(pts, axis=0)
    ptsCentered = pts - ptsMean
    ptsStd = np.sqrt(np.sum(np.sum(ptsCentered ** 2, axis=1))/(2*len(pts)))
    M = np.array([[1/ptsStd, 0, 0],
                [0, 1/ptsStd, 0],
                [0, 0, 1]]) @ np.array([[1, 0, -ptsMean[0]],
                                        [0, 1, -ptsMean[1]],
                                        [0, 0, 1]])
    return M





masked_pts1= consensus_pts1
masked_pts2 = consensus_pts2

M1 = __getNormalizingMatrix(masked_pts1)
M2 = __getNormalizingMatrix(masked_pts2)

masked_pts1 = (M1 @ np.vstack((masked_pts1.T, np.ones((1, masked_pts1.shape[0]))))).T[:, 0:2]
masked_pts2 = (M2 @ np.vstack((masked_pts2.T, np.ones((1, masked_pts2.shape[0]))))).T[:, 0:2]

print(masked_pts1.shape)


F_masked_normalized, _ = cv2.findFundamentalMat(masked_pts1, masked_pts2, cv2.FM_8POINT)
F_masked = M2.T @ F_masked_normalized @ M1
print(F_masked/ F_masked[2,2])

masked_pts1_hom = np.hstack((masked_pts1, np.ones((masked_pts1.shape[0], 1))))
masked_pts2_hom = np.hstack((masked_pts2, np.ones((masked_pts2.shape[0], 1))))
error = np.abs(np.sum(masked_pts2_hom * (F_cv @ masked_pts1_hom.T).T, axis=1))
# np.abs(np.masked_pts1_hom @ (F_masked @ masked_pts2_hom.T), axis=1))


(223, 2)
[[-1.89586435e-07 -2.97866673e-04  1.66114670e-01]
 [ 2.99485635e-04 -1.09992368e-06 -1.56928343e-01]
 [-1.66746839e-01  1.55586315e-01  1.00000000e+00]]


In [73]:
print(F)

[[-1.90761725e-07 -1.77833750e-05  9.37267206e-03]
 [ 1.88203814e-05  1.83704435e-06 -3.20876497e-03]
 [-9.68777047e-03  2.93918031e-04  1.00000000e+00]]
