# Results of Computing F matrix

In [9]:
# Imports
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from EightPoint import EightPoint
from processSequence import Sequence

## Get data

In [11]:
EPA = EightPoint()

# Load data
sequence = Sequence('./Reference_Render_cubes/Reference_Render_Translation')

['./Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0001.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0002.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0003.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0004.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0005.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0006.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0007.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0008.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0009.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0010.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation0011.png', './Reference_Render_cubes/Reference_Render_Translation\\cubes_translation00

## Find keypoints

In [12]:
im1 = sequence.images[0]
im2 = sequence.images[1]
pts1, pts2 = EPA.getMatchingPointsOpenCV(im1, im2)

In [32]:
print(pts1)

[[ 893.       393.     ]
 [ 827.       395.     ]
 [ 935.       397.     ]
 [1361.       469.     ]
 [1256.       470.     ]
 [1402.       471.     ]
 [ 825.       474.     ]
 [ 938.       475.     ]
 [ 809.       477.     ]
 [ 949.       477.     ]
 [ 951.       577.     ]
 [ 807.       578.     ]
 [ 809.       578.     ]
 [ 895.       579.     ]
 [1045.       580.     ]
 [ 793.       581.     ]
 [1256.       581.     ]
 [1403.       581.     ]
 [ 989.       582.     ]
 [ 995.       582.     ]
 [1364.       583.     ]
 [ 932.       584.     ]
 [1491.       584.     ]
 [1336.       585.     ]
 [1221.       586.     ]
 [1456.       586.     ]
 [1326.       587.     ]
 [1339.       587.     ]
 [1218.       588.     ]
 [1747.       589.     ]
 [1360.       590.     ]
 [1591.       590.     ]
 [1193.       591.     ]
 [1747.       591.     ]
 [1717.       592.     ]
 [1312.       593.     ]
 [ 934.       670.     ]
 [1045.       680.     ]
 [ 793.       681.     ]
 [ 989.       684.     ]


## Compute F using our algorithm

In [44]:

F, consensus = EPA.getFundamentalRANSAC(pts1, pts2)

F_cv, mask = cv2.findFundamentalMat(pts1, pts2, cv2.RANSAC, 1)

NORM 1.0000187842438963
NORM 1.000553572284069
Best number of inliers: 333, outliers: 83
NORM 1.0002302162905212
NORM 1.0566465090741934
NORM 1.0000278915969132
NORM 1.02470742632228
NORM 1.1543926516993241
NORM 8.783273111018378
NORM 1.0515562672401468
NORM 2.032187265591261
NORM 1.0010693989490973
NORM 1.2119189404212183
NORM 1.0289093374195055
NORM 1.341996979593712
NORM 1.0387126956630095
NORM 1.2885782278833369
NORM 1.375687436936434
NORM 9.344885432461563
NORM 1.0000128437841926
NORM 1.000553572284069
NORM 1.0173142232465175
NORM 2.1090654289622983
NORM 1.000002451633083
NORM 1.000553572284069
NORM 1.910008927955505
NORM 2.112691297325844
NORM 2.0686337741894096
NORM 1.9965922068165407
NORM 1.0752545265086553
NORM 2.6760214172548453
NORM 1.274982030262184
NORM 1.2938253926852046
NORM 1.0070186161651997
NORM 1.341996979593712
NORM 1.000277858739028
NORM 1.0079568921335047
NORM 1.0000369308066384
NORM 1.000212733458789
Best number of inliers: 341, outliers: 75
NORM 1.00502984512031

In [45]:
number_of_pts = pts1.shape[0]
consensus_set = np.arange(0, number_of_pts)
consensus_set = np.isin(consensus_set, consensus)
print(sum(consensus_set))
consensus_set



366


array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [ ]:
consensus_pts1 = pts1[consensus_set]
consensus_pts2 = pts2[consensus_set]



[[ 893.       393.     ]
 [ 827.       395.     ]
 [ 935.       397.     ]
 [1361.       469.     ]
 [1256.       470.     ]
 [1402.       471.     ]
 [ 825.       474.     ]
 [ 938.       475.     ]
 [ 809.       477.     ]
 [ 949.       477.     ]
 [ 951.       577.     ]
 [ 807.       578.     ]
 [ 809.       578.     ]
 [ 895.       579.     ]
 [1045.       580.     ]
 [ 793.       581.     ]
 [1256.       581.     ]
 [1403.       581.     ]
 [ 989.       582.     ]
 [ 995.       582.     ]
 [1364.       583.     ]
 [ 932.       584.     ]
 [1491.       584.     ]
 [1336.       585.     ]
 [1221.       586.     ]
 [1456.       586.     ]
 [1326.       587.     ]
 [1339.       587.     ]
 [1218.       588.     ]
 [1747.       589.     ]
 [1360.       590.     ]
 [1591.       590.     ]
 [1193.       591.     ]
 [1747.       591.     ]
 [1717.       592.     ]
 [1312.       593.     ]
 [ 934.       670.     ]
 [1045.       680.     ]
 [ 793.       681.     ]
 [ 989.       684.     ]


In [23]:
print(F)
print(F_cv)

[[ 3.72980897e-07 -5.23227463e-05  2.71634449e-02]
 [ 5.11986381e-05  3.05267305e-06 -4.44993502e-02]
 [-2.74326990e-02  4.18648332e-02  1.00000000e+00]]
[[ 1.48199344e-22  1.03910532e-17 -6.26578439e-15]
 [-1.03960803e-17  7.57602413e-20 -4.93913983e-03]
 [ 6.27216929e-15  4.93913983e-03 -7.10542736e-15]]


## Compare the F we calculated with F calculated from our Ransac Consensus Points on opencv's cv2.findFundamentalMat(masked_pts1, masked_pts2, cv2.FM_8POINT)

In [50]:
def __getNormalizingMatrix(pts):
    # Normalize points
    ptsMean = np.mean(pts, axis=0)
    ptsCentered = pts - ptsMean
    ptsStd = np.sqrt(np.sum(np.sum(ptsCentered ** 2, axis=1))/(2*len(pts)))
    M = np.array([[1/ptsStd, 0, 0],
                [0, 1/ptsStd, 0],
                [0, 0, 1]]) @ np.array([[1, 0, -ptsMean[0]],
                                        [0, 1, -ptsMean[1]],
                                        [0, 0, 1]])
    return M





masked_pts1= consensus_pts1
masked_pts2 = consensus_pts2

M1 = __getNormalizingMatrix(masked_pts1)
M2 = __getNormalizingMatrix(masked_pts2)

masked_pts1 = (M1 @ np.vstack((masked_pts1.T, np.ones((1, masked_pts1.shape[0]))))).T[:, 0:2]
masked_pts2 = (M2 @ np.vstack((masked_pts2.T, np.ones((1, masked_pts2.shape[0]))))).T[:, 0:2]

print(masked_pts1.shape)


F_masked_normalized, _ = cv2.findFundamentalMat(masked_pts1, masked_pts2, cv2.FM_8POINT)
F_masked = M2.T @ F_masked_normalized @ M1
print(F_masked/ F_masked[2,2])

masked_pts1_hom = np.hstack((masked_pts1, np.ones((masked_pts1.shape[0], 1))))
masked_pts2_hom = np.hstack((masked_pts2, np.ones((masked_pts2.shape[0], 1))))
error = np.abs(np.sum(masked_pts2_hom * (F_cv @ masked_pts1_hom.T).T, axis=1))
# np.abs(np.masked_pts1_hom @ (F_masked @ masked_pts2_hom.T), axis=1))


(355, 2)
[[ 1.56859390e-06  6.81960664e-03 -4.24898719e+00]
 [-6.82897660e-03  6.62338870e-05  5.61769661e+00]
 [ 4.25167930e+00 -5.65810317e+00  1.00000000e+00]]
