In [2]:
import numpy as np
import 

SyntaxError: invalid syntax (10590748.py, line 2)

In [8]:
x = np.eye(3)
x[0,2] = 9
x

array([[1., 0., 9.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:

pts1 = np.random.random((5,2))
print(pts1)
pts1_hom = np.hstack((pts1, np.ones((pts1.shape[0], 1))))
print(pts1_hom)


F = np.eye(3) * 4
print(F)
transformed_pts = (F @ pts1_hom.T).T
print(transformed_pts)

transformed_pts_adjusted = transformed_pts[:, 0:2] / transformed_pts[:, 2][:, None]
print(transformed_pts_adjusted)

[[0.92689598 0.82436364]
 [0.89557737 0.81169365]
 [0.61346799 0.88608728]
 [0.15706191 0.75339811]
 [0.50837028 0.73307046]]
[[0.92689598 0.82436364 1.        ]
 [0.89557737 0.81169365 1.        ]
 [0.61346799 0.88608728 1.        ]
 [0.15706191 0.75339811 1.        ]
 [0.50837028 0.73307046 1.        ]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
[[3.70758394 3.29745455 4.        ]
 [3.58230947 3.24677459 4.        ]
 [2.45387196 3.5443491  4.        ]
 [0.62824763 3.01359244 4.        ]
 [2.03348113 2.93228184 4.        ]]
[[0.92689598 0.82436364]
 [0.89557737 0.81169365]
 [0.61346799 0.88608728]
 [0.15706191 0.75339811]
 [0.50837028 0.73307046]]


In [37]:
def apply_matrix(pts, F):
    ''' 
    apply matrix F to the input points, first converting to homogenous
    Params:
    pts: (Nxm) matrix of points
    F: (m+1 x m+1) matrix (could be fundmental)
    '''  
    # Convert to homgenous coords  
    pts_hom = np.hstack((pts, np.ones((pts.shape[0], 1)))) # (N x m)

    # Transform by matrix F
    transformed_pts = (F @ pts_hom.T).T  # (N x m)

    # Divide by homogenous scaling
    return transformed_pts[:, 0:pts.shape[1]] / transformed_pts[:, pts.shape[1]][:, None]

In [25]:
pts1 = np.random.random((5,2))
print(pts1)

pts1_hom = np.hstack((pts1, np.ones((pts1.shape[0], 1))))
print(pts1_hom)


F = np.eye(3) * 4
print(F)
transformed_pts = (F @ pts1_hom.T).T
print(transformed_pts)

transformed_pts_adjusted = transformed_pts[:, 0:2] / transformed_pts[:, 2][:, None]
print(transformed_pts_adjusted)

[[0.10848983 0.46465733]
 [0.67805651 0.01982119]
 [0.29478836 0.25941299]
 [0.33913677 0.57593091]
 [0.10673566 0.57178743]]
[[0.10848983 0.46465733 1.        ]
 [0.67805651 0.01982119 1.        ]
 [0.29478836 0.25941299 1.        ]
 [0.33913677 0.57593091 1.        ]
 [0.10673566 0.57178743 1.        ]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
[[0.43395931 1.85862933 4.        ]
 [2.71222604 0.07928474 4.        ]
 [1.17915343 1.03765196 4.        ]
 [1.35654709 2.30372366 4.        ]
 [0.42694263 2.28714971 4.        ]]
[[0.10848983 0.46465733]
 [0.67805651 0.01982119]
 [0.29478836 0.25941299]
 [0.33913677 0.57593091]
 [0.10673566 0.57178743]]


In [38]:
fun_pts = apply_matrix(pts1, F)
print(fun_pts)

[[0.10848983 0.46465733]
 [0.67805651 0.01982119]
 [0.29478836 0.25941299]
 [0.33913677 0.57593091]
 [0.10673566 0.57178743]]


In [ ]:
apply_matrix

In [42]:
x = np.array([[1,2], [3, 3], [1, 0]])

print(np.sum(x ** 2, axis=1))
np.sum(np.sum(x ** 2, axis=1))

[ 5 18  1]


np.int64(24)

In [55]:
def calculate_dist(pts1, pts2):
    '''Calculate the distance between two sets of N-D vectors. Assumes pts is of size M x N. I.e M N-D vectors'''
    diff = pts1 - pts2
    return np.linalg.norm(diff, axis=1)


In [57]:
x = np.array([[1,2], [0,0], [2,2]])
y = np.copy(x)
y[0, 1] = 3
y[1] = [1,1]

print(x)
print(y)



print(calculate_dist(x, y))

[[1 2]
 [0 0]
 [2 2]]
[[1 3]
 [1 1]
 [2 2]]
[1.         1.41421356 0.        ]
